### ISSUE TITLE
No longer works with Slack

### ISSUE THREAD

**Issue by mdeeks** [cleverflame/bamboo-slack-notify-support#1]
Slack has a new webhook url format:
https://hooks.slack.com/services/RANDOM/RANDOM/RANDOM

They no longer provide a single webhook token so the plugin doesn't work.

**Comment by sammarx** [comment]
+1 here.

**Comment by digital11** [comment]
Hey folks, so sorry for the delay. I'm working this week on an updated version of the plugin that supports Slacks new api. Expect to see an update soon.

**Comment by esetnik** [comment]
@digital11 I'd be happy to help you support and improve this plugin if you're interested.

**Comment by sammarx** [comment]
Any more word on the plugin?

**Comment by digital11** [comment]
Yes, there is a new version available on Atlassian's Marketplace

**Comment by sammarx** [comment]
Is this addon compatible with Bamboo 5.7?

**Comment by digital11** [comment]
Yes. Compatible up to 5.8.

**Comment by sammarx** [comment]
Can you please update the plugin on the marketplace?  It's set to 5.6.2.

**Comment by digital11** [comment]
Fixed, apologies for that.

**Comment by sammarx** [comment]
Awesome, thanks again for the quick turnaround!
