### ISSUE TITLE
Reason links in deployment webhooks are not in correct format

### ISSUE THREAD

**Issue by esetnik** [cleverflame/bamboo-slack-notify-support#2]
Steps to reproduce:
1. Create a successful deployment notification from bamboo to slack
2. Deploy and receive notification in slack
3. Check the "Reason" field, it is html, not slack text link format

Example:

```
Reason
Child of <a href="https://bamboo.sumu.io/browse/ST-TP2-18">ST-TP2-18</a>
```

Correct format as per [Slack documentation](https://api.slack.com/incoming-webhooks):

```
{
    "text": "<https://alert-system.com/alerts/1234|Click here> for details!"
}
```

**Comment by digital11** [comment]
Fixed in 1.1.0
